# Generated by Django 3.1.6 on 2021-03-25 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210321_1108'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.student', verbose_name='студент'),
        ),
    ]
