# Generated by Django 3.1.6 on 2021-03-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'мужской'), ('f', 'женский')], max_length=1, verbose_name='пол'),
        ),
    ]
