# Generated by Django 3.1.6 on 2021-03-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210305_1201'),
        ('accounts', '0002_auto_20210314_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume',
            field=models.TextField(blank=True, verbose_name='резюме'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'мужской'), ('f', 'женский'), ('u', 'неизвестен')], default='u', max_length=1, verbose_name='пол'),
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
    ]
