# Generated by Django 3.1.6 on 2021-03-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210215_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['seq_number'], 'verbose_name': 'занятие', 'verbose_name_plural': 'занятия'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='seq_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='порядковый номер занятия'),
        ),
    ]
