# Generated by Django 3.1.6 on 2021-02-15 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False, verbose_name='окончен')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='курс')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='студент')),
            ],
            options={
                'verbose_name': 'подписка на курс',
                'verbose_name_plural': 'подписки на курсы',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False, verbose_name='пройдено')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.coursesubscription')),
            ],
            options={
                'verbose_name': 'занятие в подписке',
                'verbose_name_plural': 'занятия в подписках',
                'unique_together': {('subscription', 'lesson')},
            },
        ),
    ]
