# Generated by Django 3.1.6 on 2021-03-03 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20210303_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningprogress',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning.coursesubscription'),
        ),
    ]
